image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # intialize conda
      conda init bash
      # Source bashrc
      source /home/gitpod/.bashrc
      # Activate the Conda environment
      conda activate genelab-utils

      # Clone the dev branch of the GeneLab_Data_Processing repository
      git clone --branch amplicon-add-runsheet-visualizations https://github.com/torres-alexis/GeneLab_Data_Processing.git

      # Clone the dev branch of the dp_tools repository
      git clone --branch amplicon_updates https://github.com/torres-alexis/dp_tools.git

      # Install dp_tools from the dev branch folder
      cd dp_tools
      pip install .
      cd ..
