image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Download miniconda
      mkdir -p ~/miniconda3
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
      bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
      rm -rf ~/miniconda3/miniconda.sh

      # Initialize miniconda
      ~/miniconda3/bin/conda init bash

      # Install mamba into the base conda environment
      conda install -n base -c conda-forge mamba --yes

      # Create the Conda environment using the conda package
      mamba create -n genelab-utils -c conda-forge -c bioconda -c defaults -c astrobiomike genelab-utils --yes

      # Activate the Conda environment
      conda activate genelab-utils

      # Clone the dev branch of the GeneLab_Data_Processing repository
      git clone --branch amplicon-add-runsheet-visualizations https://github.com/torres-alexis/GeneLab_Data_Processing.git

      # Clone the dev branch of the dp_tools repository
      git clone --branch amplicon_updates https://github.com/torres-alexis/dp_tools.git

      # Install dp_tools from the dev branch folder
      cd dp_tools
      pip install .
      cd ..




  - command: |
      # Activate the environment
      conda activate genelab-utils